### ISSUE TITLE
Dark mode background color is misplaced

### ISSUE THREAD

**Issue by rudolfbyker** [heartbeat-sh/documentation#1]
I have more heartbeats than fits on a single screen at https://rsc.heartbeat.sh/ In dark mode, when scrolling down, the dark background only applies to the first screenful of content:

![image](https://user-images.githubusercontent.com/10025342/120375245-dda3d600-c31a-11eb-9bef-f2b3f0780b95.png)

I think the `bg-gray-900` class should move from `div.h-screen` to `body`. Then it looks like this:

![image](https://user-images.githubusercontent.com/10025342/120375215-d381d780-c31a-11eb-8eeb-05c0cbddaa6d.png)

**Comment by arieroos** [comment]
Thanks @rudolfbyker 

This issue is now fixed. If the the issue persists, please force refresh the page in your browser.

**Comment by rudolfbyker** [comment]
Looking good!
