### ISSUE TITLE
Feature request: Sort by column

### ISSUE THREAD

**Issue by rudolfbyker** [heartbeat-sh/documentation#2]
Ideally, it should remember the sorting (per browser is OK, so you don't need fancy server side stuff). More specifically, I would like to sort by status, with red on top, then orange, then green.

PS: I know this is the documentation repo, but I could not find an issue tracker for the service as a whole.

**Comment by arieroos** [comment]
I have in mind to order by status by default, so that failing heartbeats are always at the top. But I can see that an order by name or an order by last beat can also be valuable

**Comment by arieroos** [comment]
OK. I deployed the following:
The dashboard now sorts by status by default. In order to sort by any other column, just click on it.
This is a hidden feature for now, as there is no GUI feedback about this, except for the sorting itself.

If it doesn't work, just force a refresh in your browser.
